### ISSUE TITLE
 New tumblr design broke addition

### ISSUE THREAD

**Issue by kyprijan** [jamesbechet/tumbTag#2]
New tumblr design broke addition. Window does not appear.

**Comment by jamesbechet** [comment]
@kyprijan it’s a bit of late reply. But I believe this issue has been fixed, can you please [update the extension](https://chrome.google.com/webstore/detail/tumblr-tag/cmbakfeanhaniakabiiabhdjkhgbbdmp) and see if that’s working for you?

**Comment by jamesbechet** [comment]
This has been fixed: https://github.com/jamesbechet/tumbTag/issues/3
